plugins:
  - "prettier-plugin-astro"

bracketSameLine: true
experimentalTernaries: true
experimentalOperatorPosition: "start"
printWidth: 100
semi: false
singleAttributePerLine: false

overrides:
  - files: "*.astro"
    options:
      parser: "astro"
